# Generated by Django 4.0.2 on 2022-03-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=300)),
                ('chucnang', models.CharField(max_length=400)),
                ('sd', models.CharField(max_length=500)),
            ],
        ),
    ]
